site_name: Ismail_Documentation
site_url: https://example.com/
theme: 
 name: "material"
plugins:
 - mkdocstrings
nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md

  
